### ISSUE TITLE
Add typescript maps to project and npm

### ISSUE THREAD

**Issue by SuperCorks** [dlevs/time#10]
This is a great library, but I'd love to have typescript maps and make them available through `@types/duration-fns`

**Comment by SuperCorks** [comment]
If I make a pull request for that would you accept it?

**Comment by dlevs** [comment]
Hey, thanks for the interest. What do you mean by "typescript maps"?

As far as I know, there's no need to publish anything to `@types/duration-fns` as it should all be bundled into the main package, since it's written in TS. Unless I'm missing something?

**Comment by SuperCorks** [comment]
Oh yeah you're right. My bad. You can close this issue lol.
