### ISSUE TITLE
Why use comma as decimal separator

### ISSUE THREAD

**Issue by wss534857356** [dlevs/time#26]
> Commas are mentioned in the spec as the preferred decimal delimiter

As described in your code, commas are used as decimal separators, but in my scenario, commas are not accepted as separators, can this separator be controlled by adding parameters?
like:
```
.toString(duration, {
  decimalDelimiter: ',' // decimalDelimiter: '.',
})
```

**Comment by dlevs** [comment]
Hi Shenshun, sounds good - I like that change!

If you raise a PR for this with the relevant test cases in `toString.test.ts`, I'd happily review it and get it published.
