### ISSUE TITLE
Durations can be incorrect in certain timezones

### ISSUE THREAD

**Issue by ryanking1809** [dlevs/time#6]
I'm currently in a GMT-5 timezone which makes the between calculation incorrect.

```js
durationFns.between('2020-02-01', '2020-03-01')
\\ returns { days: -2, months: 1 }
```

Using the UTC getters should fix this. Can do a PR tomorrow to fix.

Related, would you consider ever having `between('2020-01-31', '2020-02-29')` return `{ days: 29 }`?  Or does that overcomplicate the `between` algorithm for you?

**Comment by ryanking1809** [comment]
Turns out this is an issue with `new Date('2020-01-31')` creating the date in UTC time but I can get  around it by using `new Date(2020,1,1)` prior.

**Comment by dlevs** [comment]
Glad you found a solution.

I intended duration-fns to take timezones into account, so a day can be 25 hours long when the clocks change for Daylight Savings Time. Always happy to revisit things if that doesn't cover all use cases.

> Related, would you consider ever having between('2020-01-31', '2020-02-29') return { days: 29 }? Or does that overcomplicate the between algorithm for you?

I think that can be achieved if we implement that changes in https://github.com/dlevs/duration-fns/issues/5

It looks useful!
